#db:
#  image: postgres:latest
#  user: postgres
#  volumes:
#    - /var/lib/postgresql/data/pgdata
#  environment:
#    POSTGRES_USER: "arachnid"
#    POSTGRES_PASSWORD: "devious8ob8"
#    PGDATA: '/var/lib/postgresql/data/pgdata'
prime:
  build: .
#  links:
#    - db:babel
  ports:
    - "80:80"
    - "443:443"
  net: "host"
  extra_hosts:
    - "babel:10.143.114.177"
  environment:
   S3_BUCKET: 'arachid-results'
   AC_CONFIG: 'development'
   REDIS_URL: 'redis://localhost:6379'
   DB_URL: 'postgresql://arachnid:devious8ob8@babel/arachnid'
   AWS_ACCESS_KEY_ID_PVLL: 'AKIAIXDDAEVM2ECFIPTA'
   AWS_SECRET_ACCESS_KEY_PVLL: '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'