---
## Data volume container to support persistent data in redis.
#data:
#  image: postgres:latest
#  volumes:
#    - /data

# The Postgres container holding the latest version of postgres and
# binds to the storage volume, pgdata where persistent data is kept.
db:
  restart: always
  dns: 8.8.8.8
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - /var/run/postgresql
    - /var/lib/postgresql/data
#  volumes_from:
#    - data:rw
  environment:
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: ''
    LC_ALL: 'en_US.utf8'
#    PGDATA: '/var/lib/postgresql/data'

redis:
  restart: always
  dns: 8.8.8.8
  image: redis:latest
  ports:
    - "6379:6379"
  environment:
    LC_ALL: 'en_US.utf8'

# Prime is the main application, which up execution will run the make
# command within the container, with a default target of 'test' if not
# otherwise overridden on the command line.
prime:
  restart: always
  dns: 8.8.8.8
  build: .
  links:
    - db:babel
    - redis:redis
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - db:rw
#  extra_hosts:
#    - "babel:10.143.114.177"
  environment:
   PRIME_DB_USER: 'arachnid'
   PRIME_DB_PASS: ''
   S3_BUCKET: 'arachid-results'
   AC_CONFIG: 'development'
   REDIS_URL: 'redis://redis:6379'
   DB_URL: 'postgresql://arachnid@babel/arachnid'
   AWS_ACCESS_KEY_ID_PVLL: 'AKIAIXDDAEVM2ECFIPTA'
   AWS_SECRET_ACCESS_KEY_PVLL: '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'
   LC_ALL: 'en_US.utf8'

