"""empty message

Revision ID: 1057ecaf70b2
Revises: 3556e7171d93
Create Date: 2016-01-07 11:13:08.521545

"""

# revision identifiers, used by Alembic.
revision = '1057ecaf70b2'
down_revision = '3556e7171d93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_location', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_location')
    ### end Alembic commands ###
