"""empty message

Revision ID: 1129bd0b019
Revises: 20f2fcc1cdc0
Create Date: 2016-01-20 14:21:16.395976

"""

# revision identifiers, used by Alembic.
revision = '1129bd0b019'
down_revision = '20f2fcc1cdc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_prospect', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_prospect', 'prospect_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
