"""empty message

Revision ID: 116d7f936250
Revises: 37733dd233c7
Create Date: 2016-01-13 21:56:12.176589

"""

# revision identifiers, used by Alembic.
revision = '116d7f936250'
down_revision = '37733dd233c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_created', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_created')
    ### end Alembic commands ###
