"""empty message

Revision ID: 123fbc701117
Revises: 4b9238e4ee7
Create Date: 2014-12-08 16:02:28.771319

"""

# revision identifiers, used by Alembic.
revision = '123fbc701117'
down_revision = '4b9238e4ee7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_id', sa.String(length=1024), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('location_raw', sa.String(), nullable=True),
    sa.Column('industry', sa.Integer(), nullable=True),
    sa.Column('industry_raw', sa.String(length=1024), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.Column('connections', sa.Integer(), nullable=True),
    sa.Column('people_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['industry'], ['industry.id'], ),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.Integer(), nullable=True),
    sa.Column('company_raw', sa.String(length=1024), nullable=True),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect_school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('school', sa.Integer(), nullable=True),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('school_raw', sa.String(length=1024), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('body_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['school'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_school')
    op.drop_table('job')
    op.drop_table('prospect')
    op.drop_table('school')
    op.drop_table('industry')
    op.drop_table('company')
    op.drop_table('location')
    ### end Alembic commands ###
