"""empty message

Revision ID: 14ddbee97789
Revises: 2e2fc268556
Create Date: 2015-12-11 19:21:46.330768

"""

# revision identifiers, used by Alembic.
revision = '14ddbee97789'
down_revision = '2e2fc268556'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('glassdoor_salary', sa.Integer(), nullable=True))
    op.add_column('prospect', sa.Column('indeed_salary', sa.Integer(), nullable=True))
    op.drop_column('prospect', 'salary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('prospect', 'indeed_salary')
    op.drop_column('prospect', 'glassdoor_salary')
    ### end Alembic commands ###
