"""empty message

Revision ID: 1d7c5019b186
Revises: None
Create Date: 2015-02-23 17:30:28.060637

"""

# revision identifiers, used by Alembic.
revision = '1d7c5019b186'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_type',
    sa.Column('client_type_id', sa.INTEGER(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('good', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('client_type_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['client_type.client_type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_prospect_id'), 'clients', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_clients_type_id'), 'clients', ['type_id'], unique=False)
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    op.drop_column(u'industry', 'count')
    op.drop_column(u'location', 'count')
    op.create_foreign_key(None, 'prospect', 'location', ['location'], ['id'])
    op.create_foreign_key(None, 'prospect', 'industry', ['industry'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.add_column(u'location', sa.Column('count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column(u'industry', sa.Column('count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_type_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_prospect_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('client_type')
    ### end Alembic commands ###
