"""empty message

Revision ID: 21cbf3906d2f
Revises: 2501ea90c54f
Create Date: 2015-12-12 16:43:37.023126

"""

# revision identifiers, used by Alembic.
revision = '21cbf3906d2f'
down_revision = '2501ea90c54f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('main_profile_image', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('main_profile_url', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('profile_image_urls', postgresql.JSONB(), nullable=True))
    op.drop_column('prospect', 'url')
    op.drop_column('prospect', 'image_url')
    op.drop_column('prospect', 'image_urls')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('image_urls', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('prospect', 'profile_image_urls')
    op.drop_column('prospect', 'main_profile_url')
    op.drop_column('prospect', 'main_profile_image')
    ### end Alembic commands ###
