"""empty message

Revision ID: 22337b9707bf
Revises: 51f5c963e91d
Create Date: 2015-12-13 06:53:18.166589

"""

# revision identifiers, used by Alembic.
revision = '22337b9707bf'
down_revision = '51f5c963e91d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_prospect', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_column('client_prospect', 'email_addresses')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_prospect', sa.Column('email_addresses', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.drop_column('client_prospect', 'updated')
    ### end Alembic commands ###
