"""empty message

Revision ID: 2501ea90c54f
Revises: 4f099ffa71cf
Create Date: 2015-12-11 23:15:30.705967

"""

# revision identifiers, used by Alembic.
revision = '2501ea90c54f'
down_revision = '4f099ffa71cf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('image_urls', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'image_urls')
    ### end Alembic commands ###
