"""empty message

Revision ID: 28be340bef5d
Revises: 4d88a4c3ced5
Create Date: 2016-01-05 11:53:51.808498

"""

# revision identifiers, used by Alembic.
revision = '28be340bef5d'
down_revision = '4d88a4c3ced5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    ### end Alembic commands ###
