"""empty message

Revision ID: 2a7cdeab308d
Revises: c4b7078341e
Create Date: 2016-01-14 02:36:21.252447

"""

# revision identifiers, used by Alembic.
revision = '2a7cdeab308d'
down_revision = 'c4b7078341e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unique_contacts_uploaded', sa.Integer(), nullable=True))
    op.drop_column('users', 'contacts_uploaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contacts_uploaded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'unique_contacts_uploaded')
    ### end Alembic commands ###
