"""empty message

Revision ID: 2e2fc268556
Revises: 1cc4bfd95597
Create Date: 2015-12-11 17:19:44.595314

"""

# revision identifiers, used by Alembic.
revision = '2e2fc268556'
down_revision = '1cc4bfd95597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    ### end Alembic commands ###
