"""empty message

Revision ID: 2efbfadbd83c
Revises: None
Create Date: 2016-01-25 12:31:09.759849

"""

# revision identifiers, used by Alembic.
revision = '2efbfadbd83c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p200_approved', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('p200_submitted_to_manager', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p200_submitted_to_manager')
    op.drop_column('users', 'p200_approved')
    ### end Alembic commands ###
