"""empty message

Revision ID: 31a98c7402f1
Revises: 88d206a19c2
Create Date: 2015-01-27 13:51:30.033212

"""

# revision identifiers, used by Alembic.
revision = '31a98c7402f1'
down_revision = '88d206a19c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_id', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_id')
    ### end Alembic commands ###
