"""empty message

Revision ID: 3556e7171d93
Revises: None
Create Date: 2016-01-05 13:29:03.778143

"""

# revision identifiers, used by Alembic.
revision = '3556e7171d93'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudsponge_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=500), nullable=True),
    sa.Column('account_email', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=500), nullable=True),
    sa.Column('service', sa.String(length=500), nullable=True),
    sa.Column('contact', postgresql.JSONB(), nullable=True),
    sa.Column('user_firstname', sa.String(length=500), nullable=True),
    sa.Column('user_lastname', sa.String(length=500), nullable=True),
    sa.Column('user_url', sa.String(length=500), nullable=True),
    sa.Column('user_location', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloudsponge_raw_account_email'), 'cloudsponge_raw', ['account_email'], unique=False)
    op.create_index(op.f('ix_cloudsponge_raw_contact_email'), 'cloudsponge_raw', ['contact_email'], unique=False)
    op.create_index(op.f('ix_cloudsponge_raw_service'), 'cloudsponge_raw', ['service'], unique=False)
    op.create_index(op.f('ix_cloudsponge_raw_user_email'), 'cloudsponge_raw', ['user_email'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('linkedin_name', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_id', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_image_url', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_location_raw', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_headline', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_industry_raw', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_connections', sa.Integer(), nullable=True),
    sa.Column('linkedin_json', postgresql.JSONB(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('indeed_salary', sa.Integer(), nullable=True),
    sa.Column('glassdoor_salary', sa.Integer(), nullable=True),
    sa.Column('dob_min_year', sa.Integer(), nullable=True),
    sa.Column('dob_max_year', sa.Integer(), nullable=True),
    sa.Column('email_addresses', postgresql.JSONB(), nullable=True),
    sa.Column('profile_image_urls', postgresql.JSONB(), nullable=True),
    sa.Column('company', sa.String(length=1024), nullable=True),
    sa.Column('company_website', sa.String(length=1024), nullable=True),
    sa.Column('company_headquarters', sa.String(length=1024), nullable=True),
    sa.Column('job', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('main_profile_image', sa.String(length=1024), nullable=True),
    sa.Column('main_profile_url', sa.String(length=1024), nullable=True),
    sa.Column('mailto', sa.String(length=1024), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('facebook', sa.String(length=1024), nullable=True),
    sa.Column('twitter', sa.String(length=1024), nullable=True),
    sa.Column('angel', sa.String(length=1024), nullable=True),
    sa.Column('flickr', sa.String(length=1024), nullable=True),
    sa.Column('soundcloud', sa.String(length=1024), nullable=True),
    sa.Column('slideshare', sa.String(length=1024), nullable=True),
    sa.Column('plus', sa.String(length=1024), nullable=True),
    sa.Column('pinterest', sa.String(length=1024), nullable=True),
    sa.Column('amazon', sa.String(length=1024), nullable=True),
    sa.Column('linkedin', sa.String(length=1024), nullable=True),
    sa.Column('foursquare', sa.String(length=1024), nullable=True),
    sa.Column('github', sa.String(length=1024), nullable=True),
    sa.Column('industry_category', sa.String(length=100), nullable=True),
    sa.Column('industry_icon', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('college_grad', sa.Boolean(), nullable=True),
    sa.Column('wealthscore', sa.Integer(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_linkedin_id'), 'prospect', ['linkedin_id'], unique=False)
    op.create_index(op.f('ix_prospect_linkedin_url'), 'prospect', ['linkedin_url'], unique=False)
    op.create_index(op.f('ix_prospect_updated'), 'prospect', ['updated'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.String(length=1024), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('degree', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_prospect_id'), 'education', ['prospect_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default='FALSE', nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('linkedin_id', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('linkedin_email', sa.String(length=1024), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('onboarding_code', sa.String(length=40), nullable=True),
    sa.Column('hiring_screen_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('p200_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('json', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_prospect_id'), 'job', ['prospect_id'], unique=False)
    op.create_table('client_prospect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('good', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('extended', sa.Boolean(), nullable=True),
    sa.Column('referrers', postgresql.JSONB(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('common_schools', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_prospect_prospect_id'), 'client_prospect', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_client_prospect_user_id'), 'client_prospect', ['user_id'], unique=False)
    op.create_table('managers',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('json', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_index(op.f('ix_managers_user_id'), 'managers', ['user_id'], unique=False)
    op.create_table('manager_users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.manager_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_manager_users_manager_id'), 'manager_users', ['manager_id'], unique=False)
    op.create_index(op.f('ix_manager_users_user_id'), 'manager_users', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_users_user_id'), table_name='manager_users')
    op.drop_index(op.f('ix_manager_users_manager_id'), table_name='manager_users')
    op.drop_table('manager_users')
    op.drop_index(op.f('ix_managers_user_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_client_prospect_user_id'), table_name='client_prospect')
    op.drop_index(op.f('ix_client_prospect_prospect_id'), table_name='client_prospect')
    op.drop_table('client_prospect')
    op.drop_index(op.f('ix_job_prospect_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_education_prospect_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_prospect_updated'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_linkedin_url'), table_name='prospect')
    op.drop_index(op.f('ix_prospect_linkedin_id'), table_name='prospect')
    op.drop_table('prospect')
    op.drop_table('customers')
    op.drop_index(op.f('ix_cloudsponge_raw_user_email'), table_name='cloudsponge_raw')
    op.drop_index(op.f('ix_cloudsponge_raw_service'), table_name='cloudsponge_raw')
    op.drop_index(op.f('ix_cloudsponge_raw_contact_email'), table_name='cloudsponge_raw')
    op.drop_index(op.f('ix_cloudsponge_raw_account_email'), table_name='cloudsponge_raw')
    op.drop_table('cloudsponge_raw')
    ### end Alembic commands ###
