"""empty message

Revision ID: 37733dd233c7
Revises: 5a7005913367
Create Date: 2016-01-13 21:21:20.316134

"""

# revision identifiers, used by Alembic.
revision = '37733dd233c7'
down_revision = '5a7005913367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contacts_uploaded', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contacts_uploaded')
    ### end Alembic commands ###
