"""empty message

Revision ID: 382954430a81
Revises: 3cfe8e64ecd5
Create Date: 2016-01-07 15:41:22.320398

"""

# revision identifiers, used by Alembic.
revision = '382954430a81'
down_revision = '3cfe8e64ecd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('name', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'name')
    ### end Alembic commands ###
