"""empty message

Revision ID: 3cfe8e64ecd5
Revises: 47f5c37832e3
Create Date: 2016-01-07 15:10:11.956639

"""

# revision identifiers, used by Alembic.
revision = '3cfe8e64ecd5'
down_revision = '47f5c37832e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    ### end Alembic commands ###
