"""empty message

Revision ID: 406e0119ab65
Revises: None
Create Date: 2015-02-24 04:29:32.993933

"""

# revision identifiers, used by Alembic.
revision = '406e0119ab65'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_list_user_id'), 'client_list', ['user_id'], unique=False)
    op.create_table('client_prospect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_list_id', sa.Integer(), nullable=True),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('good', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_list_id'], ['client_list.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_prospect_client_list_id'), 'client_prospect', ['client_list_id'], unique=False)
    op.create_index(op.f('ix_client_prospect_prospect_id'), 'client_prospect', ['prospect_id'], unique=False)
    #op.drop_table('location_temp')
    #op.drop_column(u'industry', 'count')
    #op.create_foreign_key(None, 'prospect', 'industry', ['industry'], ['id'])
    op.add_column(u'users', sa.Column('json', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'json')
    op.drop_constraint(None, 'prospect', type_='foreignkey')
    op.add_column(u'industry', sa.Column('count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table('location_temp',
    sa.Column('location_raw', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_client_prospect_prospect_id'), table_name='client_prospect')
    op.drop_index(op.f('ix_client_prospect_client_list_id'), table_name='client_prospect')
    op.drop_table('client_prospect')
    op.drop_index(op.f('ix_client_list_user_id'), table_name='client_list')
    op.drop_table('client_list')
    ### end Alembic commands ###
