"""empty message

Revision ID: 41a190f59989
Revises: 1129bd0b019
Create Date: 2016-01-20 21:51:29.360691

"""

# revision identifiers, used by Alembic.
revision = '41a190f59989'
down_revision = '1129bd0b019'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_managers_user_id', table_name='managers')
    op.create_index(op.f('ix_managers_user_id'), 'managers', ['user_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_user_id'), table_name='managers')
    op.create_index('ix_managers_user_id', 'managers', ['user_id'], unique=False)
    ### end Alembic commands ###
