"""empty message

Revision ID: 41da19fb2206
Revises: 2efbfadbd83c
Create Date: 2016-01-28 21:07:38.013134

"""

# revision identifiers, used by Alembic.
revision = '41da19fb2206'
down_revision = '2efbfadbd83c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prospect_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'prospect', ['prospect_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'prospect_id')
    ### end Alembic commands ###
