"""empty message

Revision ID: 46dbc902bbd0
Revises: 5638121d74b0
Create Date: 2015-12-21 15:10:40.454822

"""

# revision identifiers, used by Alembic.
revision = '46dbc902bbd0'
down_revision = '5638121d74b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'stars',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'stars',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
