"""empty message

Revision ID: 47a16fb1c0f8
Revises: 33d93339920
Create Date: 2016-01-16 00:34:27.648507

"""

# revision identifiers, used by Alembic.
revision = '47a16fb1c0f8'
down_revision = '33d93339920'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_statistics', postgresql.JSONB(), nullable=True))
    op.drop_column('users', 'json')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('json', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.drop_column('users', '_statistics')
    ### end Alembic commands ###
