"""empty message

Revision ID: 47f5c37832e3
Revises: 1057ecaf70b2
Create Date: 2016-01-07 11:50:10.231325

"""

# revision identifiers, used by Alembic.
revision = '47f5c37832e3'
down_revision = '1057ecaf70b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p200_started', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p200_started')
    ### end Alembic commands ###
