"""empty message

Revision ID: 4b9238e4ee7
Revises: None
Create Date: 2014-12-08 15:10:25.807762

"""

# revision identifiers, used by Alembic.
revision = '4b9238e4ee7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
