"""empty message

Revision ID: 4bccd73e0794
Revises: 9c63e981fb6
Create Date: 2015-12-11 15:14:38.001623

"""

# revision identifiers, used by Alembic.
revision = '4bccd73e0794'
down_revision = '9c63e981fb6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_prospect', sa.Column('email_addresses', postgresql.JSONB(), nullable=True))
    op.add_column('client_prospect', sa.Column('extended', sa.Boolean(), nullable=True))
    op.add_column('client_prospect', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('education', sa.Column('school_name', sa.String(length=1024), nullable=True))
    op.drop_index('ix_education_school_id', table_name='education')
    op.drop_index('ix_education_school_linkedin_id', table_name='education')
    op.drop_constraint(u'education_school_linkedin_id_fkey', 'education', type_='foreignkey')
    op.drop_constraint(u'education_school_id_fkey', 'education', type_='foreignkey')
    op.drop_column('education', 'school_linkedin_id')
    op.drop_column('education', 'school_id')
    op.add_column('job', sa.Column('company_name', sa.String(length=1024), nullable=True))
    op.drop_index('ix_job_company_id', table_name='job')
    op.drop_index('ix_job_company_linkedin_id', table_name='job')
    op.drop_constraint(u'job_company_linkedin_id_fkey', 'job', type_='foreignkey')
    op.drop_constraint(u'job_company_id_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'indeed_salary')
    op.drop_column('job', 'glassdoor_salary')
    op.drop_column('job', 'fts_title')
    op.drop_column('job', 'company_linkedin_id')
    op.drop_column('job', 'company_id')
    op.add_column('prospect', sa.Column('age', sa.Float(), nullable=True))
    op.add_column('prospect', sa.Column('amazon', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('angel', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('college_grad', sa.Boolean(), nullable=True))
    op.add_column('prospect', sa.Column('common_school', sa.String(length=200), nullable=True))
    op.add_column('prospect', sa.Column('company', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('dob_max', sa.Date(), nullable=True))
    op.add_column('prospect', sa.Column('dob_min', sa.Date(), nullable=True))
    op.add_column('prospect', sa.Column('email_addresses', postgresql.JSONB(), nullable=True))
    op.add_column('prospect', sa.Column('facebook', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('flickr', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('foursquare', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('gender', sa.String(length=15), nullable=True))
    op.add_column('prospect', sa.Column('github', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('industry_category', sa.String(length=100), nullable=True))
    op.add_column('prospect', sa.Column('industry_icon', sa.String(length=200), nullable=True))
    op.add_column('prospect', sa.Column('job', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_connections', sa.Integer(), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_headline', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_image_url', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_industry_raw', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_location_raw', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_name', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('linkedin_url', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('mailto', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('prospect', sa.Column('pinterest', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('plus', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('prospect', sa.Column('slideshare', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('soundcloud', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('twitter', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('wealthscore', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prospect_linkedin_url'), 'prospect', ['linkedin_url'], unique=False)
    op.drop_index('ix_prospect_s3_key', table_name='prospect')
    op.drop_index('ix_prospect_url', table_name='prospect')
    op.drop_constraint(u'prospect_industry_fkey', 'prospect', type_='foreignkey')
    op.drop_constraint(u'prospect_location_id_fkey', 'prospect', type_='foreignkey')
    op.drop_column('prospect', 'connections')
    op.drop_column('prospect', 'google_network_search')
    op.drop_column('prospect', 'complete')
    op.drop_column('prospect', 'all_email_addresses')
    op.drop_column('prospect', 'is_male')
    op.drop_column('prospect', 's3_key')
    op.drop_column('prospect', 'pipl_contact_response')
    op.drop_column('prospect', 'pipl_response')
    op.drop_column('prospect', 'headline')
    op.drop_column('prospect', 'json')
    op.drop_column('prospect', 'location_raw')
    op.drop_column('prospect', 'location_id')
    op.drop_column('prospect', 'industry_raw')
    ### end Alembic commands ###
    op.drop_table('location', )
    op.drop_table('job_titles')
    op.drop_table('linkedin_companies')
    op.drop_table('industry')
    op.drop_table('school')
    op.drop_table('company')
    op.drop_table('linkedin_schools')
    op.drop_table('prospect_location')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('industry_raw', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('location_raw', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('json', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('headline', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('pipl_response', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('pipl_contact_response', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('s3_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('is_male', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('all_email_addresses', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('google_network_search', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('prospect', sa.Column('connections', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'prospect_location_id_fkey', 'prospect', 'location', ['location_id'], ['id'])
    op.create_foreign_key(u'prospect_industry_fkey', 'prospect', 'industry', ['industry'], ['id'])
    op.create_index('ix_prospect_url', 'prospect', ['url'], unique=False)
    op.create_index('ix_prospect_s3_key', 'prospect', ['s3_key'], unique=False)
    op.drop_index(op.f('ix_prospect_linkedin_url'), table_name='prospect')
    op.drop_column('prospect', 'wealthscore')
    op.drop_column('prospect', 'twitter')
    op.drop_column('prospect', 'soundcloud')
    op.drop_column('prospect', 'slideshare')
    op.drop_column('prospect', 'salary')
    op.drop_column('prospect', 'plus')
    op.drop_column('prospect', 'pinterest')
    op.drop_column('prospect', 'phone')
    op.drop_column('prospect', 'mailto')
    op.drop_column('prospect', 'linkedin_url')
    op.drop_column('prospect', 'linkedin_name')
    op.drop_column('prospect', 'linkedin_location_raw')
    op.drop_column('prospect', 'linkedin_industry_raw')
    op.drop_column('prospect', 'linkedin_image_url')
    op.drop_column('prospect', 'linkedin_headline')
    op.drop_column('prospect', 'linkedin_connections')
    op.drop_column('prospect', 'linkedin')
    op.drop_column('prospect', 'job')
    op.drop_column('prospect', 'industry_icon')
    op.drop_column('prospect', 'industry_category')
    op.drop_column('prospect', 'github')
    op.drop_column('prospect', 'gender')
    op.drop_column('prospect', 'foursquare')
    op.drop_column('prospect', 'flickr')
    op.drop_column('prospect', 'facebook')
    op.drop_column('prospect', 'email_addresses')
    op.drop_column('prospect', 'dob_min')
    op.drop_column('prospect', 'dob_max')
    op.drop_column('prospect', 'company')
    op.drop_column('prospect', 'common_school')
    op.drop_column('prospect', 'college_grad')
    op.drop_column('prospect', 'angel')
    op.drop_column('prospect', 'amazon')
    op.drop_column('prospect', 'age')
    op.add_column('job', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('company_linkedin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('fts_title', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('glassdoor_salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('indeed_salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'job_company_id_fkey', 'job', 'company', ['company_id'], ['id'])
    op.create_foreign_key(u'job_company_linkedin_id_fkey', 'job', 'linkedin_companies', ['company_linkedin_id'], ['id'])
    op.create_index('ix_job_company_linkedin_id', 'job', ['company_linkedin_id'], unique=False)
    op.create_index('ix_job_company_id', 'job', ['company_id'], unique=False)
    op.drop_column('job', 'company_name')
    op.add_column('education', sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('education', sa.Column('school_linkedin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'education_school_id_fkey', 'education', 'school', ['school_id'], ['id'])
    op.create_foreign_key(u'education_school_linkedin_id_fkey', 'education', 'linkedin_schools', ['school_linkedin_id'], ['id'])
    op.create_index('ix_education_school_linkedin_id', 'education', ['school_linkedin_id'], unique=False)
    op.create_index('ix_education_school_id', 'education', ['school_id'], unique=False)
    op.drop_column('education', 'school_name')
    op.drop_column('client_prospect', 'stars')
    op.drop_column('client_prospect', 'extended')
    op.drop_column('client_prospect', 'email_addresses')
    op.create_table('prospect_location',
    sa.Column('prospect_id', sa.BIGINT(), nullable=False),
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('prospect_id', 'location_id', name=u'prospect_location_pkey')
    )
    op.create_table('linkedin_schools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=900), autoincrement=False, nullable=True),
    sa.Column('pretty_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=900), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'linkedin_schools_pkey')
    )
    op.create_table('company',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'company_pkey')
    )
    op.create_table('school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'school_pkey')
    )
    op.create_table('industry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'industry_pkey')
    )
    op.create_table('linkedin_companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=900), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('company_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pretty_url', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=900), autoincrement=False, nullable=True),
    sa.Column('founded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('headquarters', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('min_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specialties', postgresql.ARRAY(VARCHAR(length=200)), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clearbit_response', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'linkedin_companies_pkey')
    )
    op.create_table('job_titles',
    sa.Column('title', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('indeed_salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('glassdoor_salary', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('title', name=u'job_titles_pkey')
    )
    op.create_table('location',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'location_pkey')
    )
    ### end Alembic commands ###
