"""empty message

Revision ID: 4d88a4c3ced5
Revises: 501f9525b98c
Create Date: 2016-01-05 11:11:34.346464

"""

# revision identifiers, used by Alembic.
revision = '4d88a4c3ced5'
down_revision = '501f9525b98c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('p200_completed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'p200_completed')
    ### end Alembic commands ###
