"""empty message

Revision ID: 4ecb04f9d1cf
Revises: a9180d13c47
Create Date: 2016-01-22 19:12:54.807043

"""

# revision identifiers, used by Alembic.
revision = '4ecb04f9d1cf'
down_revision = 'a9180d13c47'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_sources', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_sources')
    ### end Alembic commands ###
