"""empty message

Revision ID: 501f9525b98c
Revises: 795df9b2a5c
Create Date: 2016-01-05 10:55:58.702710

"""

# revision identifiers, used by Alembic.
revision = '501f9525b98c'
down_revision = '795df9b2a5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hiring_screen_completed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hiring_screen_completed')
    ### end Alembic commands ###
