"""empty message

Revision ID: 51f5c963e91d
Revises: 21cbf3906d2f
Create Date: 2015-12-13 01:21:06.061068

"""

# revision identifiers, used by Alembic.
revision = '51f5c963e91d'
down_revision = '21cbf3906d2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'industry')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('industry', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
