"""empty message

Revision ID: 53b6dddd1955
Revises: eab78500ec0
Create Date: 2015-01-26 13:32:11.921477

"""

# revision identifiers, used by Alembic.
revision = '53b6dddd1955'
down_revision = 'eab78500ec0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    ### end Alembic commands ###
