"""empty message

Revision ID: 5638121d74b0
Revises: 298fdb4f1940
Create Date: 2015-12-21 15:09:42.856318

"""

# revision identifiers, used by Alembic.
revision = '5638121d74b0'
down_revision = '298fdb4f1940'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
