"""empty message

Revision ID: 58423c7d2bae
Revises: 4bccd73e0794
Create Date: 2015-12-11 16:32:19.568801

"""

# revision identifiers, used by Alembic.
revision = '58423c7d2bae'
down_revision = '4bccd73e0794'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('linkedin_json', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'linkedin_json')
    ### end Alembic commands ###
