"""empty message

Revision ID: 58d483953e52
Revises: f779a7b4352
Create Date: 2015-12-13 19:26:08.406498

"""

# revision identifiers, used by Alembic.
revision = '58d483953e52'
down_revision = 'f779a7b4352'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('client_prospect', 'stars',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_prospect', 'stars',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_prospect', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
