"""empty message

Revision ID: 5a7005913367
Revises: 7121b35379d
Create Date: 2016-01-12 15:14:35.871704

"""

# revision identifiers, used by Alembic.
revision = '5a7005913367'
down_revision = '7121b35379d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prospect_industry_category'), 'prospect', ['industry_category'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prospect_industry_category'), table_name='prospect')
    ### end Alembic commands ###
