"""empty message

Revision ID: 7121b35379d
Revises: 382954430a81
Create Date: 2016-01-08 00:02:03.108367

"""

# revision identifiers, used by Alembic.
revision = '7121b35379d'
down_revision = '382954430a81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('us_state', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'us_state')
    ### end Alembic commands ###
