"""empty message

Revision ID: 77b910bb9e0
Revises: 28be340bef5d
Create Date: 2016-01-05 12:43:17.486962

"""

# revision identifiers, used by Alembic.
revision = '77b910bb9e0'
down_revision = '28be340bef5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_email', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_email')
    ### end Alembic commands ###
