"""empty message

Revision ID: 795df9b2a5c
Revises: 58ccc7f768ee
Create Date: 2015-12-27 22:32:24.902440

"""

# revision identifiers, used by Alembic.
revision = '795df9b2a5c'
down_revision = '58ccc7f768ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospect', sa.Column('company_headquarters', sa.String(length=1024), nullable=True))
    op.add_column('prospect', sa.Column('company_website', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'company_website')
    op.drop_column('prospect', 'company_headquarters')
    ### end Alembic commands ###
