"""empty message

Revision ID: 88d206a19c2
Revises: 53b6dddd1955
Create Date: 2015-01-26 13:32:58.640162

"""

# revision identifiers, used by Alembic.
revision = '88d206a19c2'
down_revision = '53b6dddd1955'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'customers', ['customer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'customer_id')
    ### end Alembic commands ###
