"""empty message

Revision ID: 9c63e981fb6
Revises: 33f5c4ca8831
Create Date: 2015-12-11 11:03:43.083076

"""

# revision identifiers, used by Alembic.
revision = '9c63e981fb6'
down_revision = '33f5c4ca8831'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_gender')
    op.drop_table('prospect_wealthscore')
    op.add_column('client_prospect', sa.Column('lead_score', sa.Integer(), nullable=False))
    op.add_column('client_prospect', sa.Column('referrers', postgresql.JSON(), nullable=True))
    op.add_column('prospect', sa.Column('is_male', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospect', 'is_male')
    op.drop_column('client_prospect', 'referrers')
    op.drop_column('client_prospect', 'lead_score')
    op.create_table('prospect_wealthscore',
    sa.Column('prospect_id', sa.BIGINT(), nullable=False),
    sa.Column('wealthscore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prospect_id', name=u'prospect_wealthscore_pkey')
    )
    op.create_table('prospect_gender',
    sa.Column('prospect_id', sa.BIGINT(), nullable=False),
    sa.Column('gender', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prospect_id', name=u'prospect_gender_pkey')
    )
    ### end Alembic commands ###
