"""empty message

Revision ID: ac47ab196f6
Revises: 31a98c7402f1
Create Date: 2015-01-27 13:57:57.611494

"""

# revision identifiers, used by Alembic.
revision = 'ac47ab196f6'
down_revision = '31a98c7402f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('linkedin_url', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'linkedin_url')
    ### end Alembic commands ###
