"""empty message

Revision ID: eab78500ec0
Revises: None
Create Date: 2015-01-23 15:20:10.194624

"""

# revision identifiers, used by Alembic.
revision = 'eab78500ec0'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default='FALSE', nullable=False),
    sa.Column('tour_completed', sa.BOOLEAN(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('s3work')
    op.drop_table('prospect_school')
    op.drop_index('education_prospect_id_idx', table_name='education')
    op.drop_index('education_school_id_idx', table_name='education')
    op.drop_index('job_company_id_idx', table_name='job')
    op.drop_index('job_prospect_id_idx', table_name='job')
    op.drop_index('linkedin_id_idx', table_name='prospect')
    op.drop_index('s3_key_idx', table_name='prospect')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('s3_key_idx', 'prospect', ['s3_key'], unique=False)
    op.create_index('linkedin_id_idx', 'prospect', ['linkedin_id'], unique=False)
    op.create_index('job_prospect_id_idx', 'job', ['prospect_id'], unique=False)
    op.create_index('job_company_id_idx', 'job', ['company_id'], unique=False)
    op.create_index('education_school_id_idx', 'education', ['school_id'], unique=False)
    op.create_index('education_prospect_id_idx', 'education', ['prospect_id'], unique=False)
    op.create_table('prospect_school',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('school', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('school_raw', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('degree', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('body_tsv', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school'], [u'school.id'], name=u'prospect_school_school_fkey'),
    sa.ForeignKeyConstraint(['user'], [u'prospect.id'], name=u'prospect_school_user_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'prospect_school_pkey')
    )
    op.create_table('s3work',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u's3work_pkey')
    )
    op.drop_table('users')
    ### end Alembic commands ###
