"""empty message

Revision ID: f779a7b4352
Revises: 26b59adb7b6
Create Date: 2015-12-13 15:37:18.291917

"""

# revision identifiers, used by Alembic.
revision = 'f779a7b4352'
down_revision = '26b59adb7b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsponge_raw', sa.Column('contact_email', sa.String(length=500), nullable=True))
    op.add_column('cloudsponge_raw', sa.Column('user_firstname', sa.String(length=500), nullable=True))
    op.add_column('cloudsponge_raw', sa.Column('user_lastname', sa.String(length=500), nullable=True))
    op.add_column('cloudsponge_raw', sa.Column('user_location', sa.String(length=500), nullable=True))
    op.add_column('cloudsponge_raw', sa.Column('user_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_cloudsponge_raw_contact_email'), 'cloudsponge_raw', ['contact_email'], unique=False)
    op.drop_index('ix_cloudsponge_raw_primary_contact_email', table_name='cloudsponge_raw')
    op.drop_column('cloudsponge_raw', 'primary_contact_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsponge_raw', sa.Column('primary_contact_email', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index('ix_cloudsponge_raw_primary_contact_email', 'cloudsponge_raw', ['primary_contact_email'], unique=False)
    op.drop_index(op.f('ix_cloudsponge_raw_contact_email'), table_name='cloudsponge_raw')
    op.drop_column('cloudsponge_raw', 'user_url')
    op.drop_column('cloudsponge_raw', 'user_location')
    op.drop_column('cloudsponge_raw', 'user_lastname')
    op.drop_column('cloudsponge_raw', 'user_firstname')
    op.drop_column('cloudsponge_raw', 'contact_email')
    ### end Alembic commands ###
