---
apiVersion: v1
kind: Service
metadata:
  name: prime-app
  labels:
    name: prime-app
spec:
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30380
      name: http
#    - protocol: TCP
#      port: 80
#      nodePort: 30381
#      name: https
  sessionAffinity: ClientIP
  type: LoadBalancer
#  loadBalancerIP: 130.211.12.49
  selector:
    name: prime-app
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: prime-ingress
#spec:
#  rules:
#  - host: nyl.advisorconnect.co
#    http:
#      paths:
#      -  backend:
#           serviceName: prime
#           servicePort: http
##           serviceName: prime
##           servicePort: https
#  tls:
#  - hosts:
#    - "*.advisorconnect.co"
#    secretName: tls
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prime-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: prime-app
  template:
    metadata:
      labels:
        name: prime-app
    spec:
      containers:
      - name: prime-app
        livenessProbe:
          exec:
            command:
            - cat
            - /proc/net/tcp
        image: gcr.io/advisorconnect-1238/aconn:1.0.21
        resources:
          requests:
            cpu: 4
            memory: "4Gi"
          limits:
            cpu: 5
            memory: "10Gi"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          protocol: TCP
          name: https
        env:
        - name: PRIME_DB_USER
          value: arachnid
        - name: PG_DB
          value: arachnid_prod
        - name: PG_HOST
          value: $(DEV_POSTGRES_SERVICE_HOST)
        - name: PRIME_DB_PASS
          value: devious8ob8
        - name: PG_PORT
          value: $(DEV_POSTGRES_SERVICE_PORT)
#          valueFrom:
#              secretKeyRef:
#                key: password
#                name: dev-postgres
        - name: S3_BUCKET
          value: "arachnid-results"
        - name: AC_CONFIG
          value: "nyl"
        - name: REDIS_URL
          value: redis://$(REDIS_MASTER_SERVICE_HOST):$(REDIS_MASTER_SERVICE_PORT)
        - name: DB_URL
          value: postgresql://$(PRIME_DB_USER):$(PRIME_DB_PASS)@$(DEV_POSTGRES_SERVICE_HOST):$(DEV_POSTGRES_SERVICE_PORT)/arachnid_prod
        - name: AWS_ACCESS_KEY_ID_PVLL
          value: "AKIAIXDDAEVM2ECFIPTA"
        - name: AWS_SECRET_ACCESS_KEY_PVLL
          value: "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"
        - name: LC_ALL
          value: "en_US.utf8"

